name: Autofill PR description

on: pull_request

jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04

    steps:
      - uses: Mo7amedSMahdi/gpt-pr-description@main
        with:
          github_token: ${{ secrets.API_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
