name: GPT PR description

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - "**"

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Build and run Docker container
        uses: docker://ghcr.io/Mo7amedSMahdi/gpt-pr-description:latest
        with:
          env:
            INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
